package com.example.unimarket.domain.enums;

public enum NotificationType {
    VENDOR_APPROVED,
    VENDOR_REJECTED,
    VENDOR_SUSPENDED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    SELLER_ORDER_CREATED,
    SELLER_ORDER_PAID,
    REVIEW_RESPONSE,
    ESCROW_HELD,
    ESCROW_RELEASED,
    ESCROW_DISPUTED,
    ESCROW_REFUNDED,
    REPORT_RESOLVED,
    EVENT_ATTENDEE_REGISTERED,
    EVENT_ATTENDEE_CANCELLED,
    EVENT_WAITLIST_PROMOTED,
    EVENT_CANCELLED,
    FULFILMENT_UPDATED
}
