import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../../js/api/client.js';
import DashboardShell from '../components/DashboardShell.jsx';
import Icon from '../components/Icon.jsx';

const DATE_FORMATTER = new Intl.DateTimeFormat('en-ZA', { dateStyle: 'medium' });
function formatLabel(value) { return String(value || '').replaceAll('_', ' ').toLocaleLowerCase('en-ZA').replace(/^./, (letter) => letter.toUpperCase()); }
function formatDate(value) { const date = value ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? DATE_FORMATTER.format(date) : 'Recently'; }
function StatusCard({ title, total, values }) { return <article className="admin-status-card"><div className="admin-status-card__heading"><h3>{title}</h3><strong>{total}</strong></div><div className="status-breakdown">{Object.entries(values || {}).map(([name, count]) => <div className="status-breakdown__row" key={name}><div><span>{formatLabel(name)}</span><strong>{count}</strong></div><span className="status-breakdown__bar"><span style={{ width: `${total ? Math.round((count / total) * 100) : 0}%` }} /></span></div>)}</div></article>; }

export default function AdminDashboardPage() {
  const [overview, setOverview] = useState(null); const [status, setStatus] = useState('loading'); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [workingId, setWorkingId] = useState('');
  const load = useCallback(async (signal) => { setStatus((current) => current === 'ready' ? 'refreshing' : 'loading'); setError(''); try { setOverview(await apiRequest('/api/v1/admin/overview', signal ? { signal } : {})); setStatus('ready'); } catch (requestError) { if (requestError.name !== 'AbortError') { setError(requestError.message); setStatus('error'); } } }, []);
  useEffect(() => { const controller = new AbortController(); load(controller.signal); return () => controller.abort(); }, [load]);
  const reviewVendor = async (vendor, vendorStatus) => { setWorkingId(`${vendor.userId}-${vendorStatus}`); setError(''); setSuccess(''); try { await apiRequest(`/api/v1/admin/vendors/${vendor.userId}/review`, { method: 'PATCH', body: { status: vendorStatus, reviewNote: `${formatLabel(vendorStatus)} through administrator review.` } }); setSuccess(`${vendor.businessName} was ${formatLabel(vendorStatus).toLocaleLowerCase()}.`); await load(); } catch (requestError) { setError(requestError.message); } finally { setWorkingId(''); } };
  const refreshing = status === 'refreshing'; const activeAccounts = overview?.accounts?.byStatus?.ACTIVE; const openModeration = overview ? overview.queues.openReports + overview.queues.disputedEscrow : null;

  return <DashboardShell role="ADMIN"><div className="admin-dashboard"><div className="admin-overview-toolbar"><div><p className="eyebrow eyebrow--line">Platform essentials</p><h2>At a glance</h2><p>Only the information needed to operate UniMarket and resolve current work.</p></div><button className="button button--dark" disabled={refreshing} type="button" onClick={() => load()}>{refreshing ? 'Refreshing…' : 'Refresh'}</button></div>{error && <div className="form-alert form-alert--error" role="alert">{error} <button type="button" onClick={() => load()}>Retry</button></div>}{success && <div className="form-alert form-alert--success" role="status">{success}</div>}
    <section className="dashboard-metrics" aria-busy={status === 'loading'}><article><span><Icon name="users" size={19} /></span><div><strong>{overview?.accounts?.total ?? '—'}</strong><small>Accounts</small></div></article><article><span><Icon name="shield" size={19} /></span><div><strong>{activeAccounts ?? '—'}</strong><small>Active</small></div></article><article><span><Icon name="store" size={19} /></span><div><strong>{overview?.queues?.pendingVendors ?? '—'}</strong><small>Vendor reviews</small></div></article><article><span><Icon name="spark" size={19} /></span><div><strong>{openModeration ?? '—'}</strong><small>Moderation items</small></div></article></section>
    {!overview ? <section className="dashboard-panel"><div className="panel-empty"><p>{status === 'error' ? 'The overview is unavailable.' : 'Loading platform essentials…'}</p></div></section> : <><div className="admin-overview-grid admin-overview-grid--primary"><StatusCard title="Account status" total={overview.accounts.total} values={overview.accounts.byStatus} /><StatusCard title="Vendor verification" total={overview.vendors.total} values={overview.vendors.byStatus} /></div><div className="dashboard-section-heading"><div><p className="eyebrow eyebrow--line">Current work</p><h2>Vendor approvals</h2></div><div className="dashboard-heading-links"><Link to="/moderation">Moderation <Icon name="arrowRight" size={13} /></Link><Link to="/admin/accounts">Account access <Icon name="arrowRight" size={13} /></Link></div></div><section className="dashboard-panel"><div className="dashboard-panel__heading"><div><p className="eyebrow eyebrow--line">Approval queue</p><h2>Pending vendors</h2></div><span>{overview.queues.pendingVendors} waiting</span></div>{overview.queues.vendorApprovals.length ? <div className="admin-list">{overview.queues.vendorApprovals.map((vendor) => <article key={vendor.vendorId}><div><strong>{vendor.businessName}</strong><small>{formatLabel(vendor.vendorType)} · Submitted {formatDate(vendor.submittedAt)}</small></div><div className="admin-action-buttons"><button className="button button--dark" disabled={Boolean(workingId)} type="button" onClick={() => reviewVendor(vendor, 'VERIFIED')}>Approve</button><button className="button button--outline" disabled={Boolean(workingId)} type="button" onClick={() => reviewVendor(vendor, 'REJECTED')}>Reject</button></div></article>)}</div> : <div className="panel-empty"><p>No vendor applications need attention.</p></div>}</section></>}
  </div></DashboardShell>;
}
