import { useCallback, useEffect, useState } from 'react';
import { getPrimaryRole } from '../../js/auth/roles.js';
import { apiRequest } from '../../js/api/client.js';
import { useAuth } from '../auth/AuthContext.jsx';
import DashboardShell from '../components/DashboardShell.jsx';

const PAGE_SIZE = 20;
const DATE_FORMATTER = new Intl.DateTimeFormat('en-ZA', { dateStyle: 'medium', timeStyle: 'short' });

function formatDate(value) {
  const date = value ? new Date(value) : null;
  return date && !Number.isNaN(date.getTime()) ? DATE_FORMATTER.format(date) : 'Time unavailable';
}

export default function NotificationsPage() {
  const auth = useAuth();
  const role = getPrimaryRole(auth.account) || 'BUYER';
  const [notifications, setNotifications] = useState([]);
  const [page, setPage] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [unread, setUnread] = useState(0);
  const [status, setStatus] = useState('loading');
  const [error, setError] = useState('');
  const [workingId, setWorkingId] = useState('');

  const load = useCallback(async (requestedPage = page, signal) => {
    setStatus('loading');
    setError('');
    const options = signal ? { signal } : {};
    try {
      const [notificationPage, unreadResponse] = await Promise.all([
        apiRequest(`/api/v1/notifications?page=${requestedPage}&size=${PAGE_SIZE}`, options),
        apiRequest('/api/v1/notifications/unread-count', options),
      ]);
      setNotifications(notificationPage.content || []);
      setPage(notificationPage.number ?? requestedPage);
      setTotalPages(notificationPage.totalPages || 0);
      setUnread(unreadResponse.unreadCount || 0);
      setStatus('ready');
    } catch (requestError) {
      if (requestError.name !== 'AbortError') {
        setError(requestError.message);
        setStatus('error');
      }
    }
  }, [page]);

  useEffect(() => {
    const controller = new AbortController();
    load(page, controller.signal);
    return () => controller.abort();
  }, [load, page]);

  const notifyCountChanged = () => window.dispatchEvent(new CustomEvent('unimarket:notifications-changed'));

  const markRead = async (notificationId) => {
    setWorkingId(notificationId);
    setError('');
    try {
      const updated = await apiRequest(`/api/v1/notifications/${notificationId}/read`, { method: 'PATCH' });
      setNotifications((current) => current.map((item) => item.id === notificationId ? updated : item));
      setUnread((current) => Math.max(0, current - 1));
      notifyCountChanged();
    } catch (requestError) {
      setError(requestError.message);
    } finally {
      setWorkingId('');
    }
  };

  const markAllRead = async () => {
    setWorkingId('all');
    setError('');
    try {
      await apiRequest('/api/v1/notifications/read-all', { method: 'PATCH' });
      await load(page);
      notifyCountChanged();
    } catch (requestError) {
      setError(requestError.message);
    } finally {
      setWorkingId('');
    }
  };

  const changePage = (nextPage) => {
    setPage(nextPage);
    window.requestAnimationFrame(() => document.getElementById('notification-inbox')?.scrollIntoView({ behavior: 'smooth' }));
  };

  return <DashboardShell role={role} eyebrow="Your account">
    <div className="workflow-page" id="notification-inbox">
      <div className="workflow-heading"><div><p className="eyebrow eyebrow--line">Account inbox</p><h2>Notifications</h2><p>{unread ? `${unread} unread ${unread === 1 ? 'notification' : 'notifications'}.` : 'Updates generated by your orders, marketplace activity, and account workflows.'}</p></div><button className="button button--dark" disabled={!unread || workingId === 'all'} type="button" onClick={markAllRead}>{workingId === 'all' ? 'Marking…' : 'Mark all read'}</button></div>
      {error && <div className="form-alert form-alert--error" role="alert">{error} <button type="button" onClick={() => load(page)}>Retry</button></div>}
      {status === 'loading' ? <section className="workflow-panel"><div className="panel-empty"><p>Loading your notification inbox…</p></div></section> : notifications.length ? <>
        <section className="workflow-panel notification-list">{notifications.map((item) => <article className={item.read ? '' : 'notification-list__item--unread'} key={item.id}><div><span>{item.type?.replaceAll('_', ' ')}</span><h3>{item.title}</h3><p>{item.message}</p><small>{formatDate(item.createdAt)}</small></div>{!item.read && <button className="button button--dark" disabled={workingId === item.id} type="button" onClick={() => markRead(item.id)}>{workingId === item.id ? 'Saving…' : 'Mark read'}</button>}</article>)}</section>
        {totalPages > 1 && <nav className="catalogue-pagination" aria-label="Notification pages"><button type="button" disabled={page === 0 || status === 'loading'} onClick={() => changePage(page - 1)}>Previous</button><span>Page <strong>{page + 1}</strong> of <strong>{totalPages}</strong></span><button type="button" disabled={page + 1 >= totalPages || status === 'loading'} onClick={() => changePage(page + 1)}>Next</button></nav>}
      </> : <section className="workflow-panel"><div className="panel-empty"><p>Your inbox is clear. New marketplace and account updates will appear here.</p></div></section>}
    </div>
  </DashboardShell>;
}
