package com.example.unimarket.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Version;

import java.time.Instant;
import java.util.UUID;

/**
 * Base class for every persistent business entity in UniMarket.
 *
 * <p>Provides the four conventions required by the data model:
 * a UUID primary key, immutable creation timestamp, update timestamp,
 * and an optimistic-locking version.
 *
 * <p>Timestamps are stored in UTC. The identifier is generated by the
 * application rather than the database so that an aggregate is fully
 * identified before it is persisted, which keeps factories and
 * builders side-effect free.
 */
@MappedSuperclass
public abstract class AuditableEntity {

    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Version
    @Column(name = "version", nullable = false)
    private Long version;

    /** Required by JPA. Not intended for application use. */
    protected AuditableEntity() {
    }

    protected AuditableEntity(UUID id) {
        this.id = (id != null) ? id : UUID.randomUUID();
    }

    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        if (this.id == null) {
            this.id = UUID.randomUUID();
        }
        this.createdAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        this.updatedAt = Instant.now();
    }

    public UUID getId() {
        return id;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public Long getVersion() {
        return version;
    }
}
